SocialAdda/SocialAdda/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.conf.urls import url, include

urlpatterns = [
    url(r'^$', views.start, name = 'start'),
    url(r'^first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

SocialAdda/first_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
#from first_app.views import confList

#Template tagging
app_name = 'first_app'

urlpatterns = [
    url(r'^$', views.confFill, name = 'confFill'),
    url(r'^confList/$', views.confList.as_view(), name = 'confList'),
    path(r'start', views.start, name = 'start'),
    path(r'adminList/', views.adminList, name = 'adminList'),
    path(r'add/<int:cpk>/', views.okok, name = "okok"),
    path(r'post/<int:cpk>/', views.postDetail, name = "postDetail"),
    path(r'delete/<int:cpk>/', views.deleteView, name = "deleteView"),
    

]

SocialAdda/first_app/models.py
from django.db import models


# Create your models here.
class Conf(models.Model):
    votes = models.IntegerField(default=0)
    heading = models.CharField(max_length=150)
    text = models.TextField(max_length=500)
    visible = models.BooleanField(default=False)
    visibleTime = models.TimeField(auto_now=True)
    

    class Meta:
        ordering = ['-visibleTime']
        
    def __str__(self):
        return self.text

class Comment(models.Model):
    text = models.CharField(max_length=500)
    id_conf = models.IntegerField(default=0)

    def __str__(self):
        return self.text

SocialAdda/first_app/forms.py
from django import forms

from first_app.models import Conf

class formName(forms.ModelForm):
    class Meta:
        model = Conf
        fields = ['heading', 'text']
        
        widgets = {
            'heading': forms.Textarea(attrs={
                'class':'',
                'style':'max-width: 100%; color: white; background-color: #1a1a1b; resize: none;',
                'placeholder':'Heading',
                'rows':'1',
                'cols':'90'
            }),
            'text': forms.Textarea(attrs={
                'class':'',
                'style':'max-width: 100%; color: white; background-color: #1a1a1b;',
                'placeholder':'Text',
                'cols': '90'
            })
        }
        # heading = forms.CharField(max_length=200)
        # text = forms.CharField(max_length=100)

class AddComment(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={
        'style':'max-width: 100%; color: white; background-color: #1a1a1b;',
        'placeholder':'Comment',
        'rows':5,
        'cols':90
    }))

    # text = forms.CharField()
    # fields = ['text']
    # widgets = {
    #     'text': forms.Textarea(attrs={
    #         'class':'',
    #         'style':'max-width: 900px; color: white; background-color: #1a1a1b;',
    #         'placeholder':'Text',
    #         'cols': '90'
    #     })
    # }
    # class Meta:
    #     model = Comment
    #     fields = ['text']
    #     widgets = {
    #         'text': forms.Textarea(attrs={
    #             'class':'',
    #             'style':'max-width: 900px; color: white; background-color: #1a1a1b;',
    #             'placeholder':'Text',
    #             'cols': '90'
    #         })
    #     }

        

class voteForm(forms.Form):
    upVote = forms.BooleanField()
    downVote = forms.BooleanField()



   

    

SocialAdda/first_app/views.py
from django.shortcuts import redirect, render
from first_app.forms import formName, AddComment
from django import forms
from first_app.models import Conf, Comment
from django.views import generic

# Create your views here.

def start(request):
    return render(request, 'first_app/start.html')

def confFill(request):
    form = formName()
    if request.method == 'POST':
        form = formName(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return start(request)
        else:
            print('ERROR IN FORM')
    cd = {'form':form}
    return render(request, 'first_app/confFill.html', cd)

def okok(request, cpk):
    pls = Conf.objects.get(pk=cpk)
    pls.visible = True
    pls.save()
    return redirect('/first_app/adminList/')



def adminList(request):
    lis = Conf.objects.all()
    if request.method == 'POST':   
        pls = Conf.objects.get(pk=request.POST.get('id'))
        pls.visible = True
        pls.save()
        
    return render(request, 'first_app/adminList.html', {'object_list':lis})


def deleteView(request, cpk):
    target = Conf.objects.get(pk = cpk)
    target.delete()
    return redirect('/first_app/adminList/')

class confList(generic.ListView):
    model = Conf
    template_name = 'first_app/confList.html'

def postDetail(request, cpk):
    all_comments = Comment.objects.all()
    target = Conf.objects.get(pk = cpk)
    commentForm = AddComment()
    if request.method == 'POST':
        newObject = Comment(text = request.POST['text'], id_conf = cpk)
        newObject.save()
        return redirect(request.META['HTTP_REFERER'])
        
    return render(request, 'first_app/postPage.html', {'conf':target, 'commentForm':commentForm, 'all_comments':all_comments})

SocialAdda/templates/first_app/adminList.html
<!DOCTYPE html>
{% extends "first_app/start.html" %}
{% block body_block %}
{% load my_extras %}
<h1>Confessions:</h1>
<div class="container text-white px-12">
    {% if object_list %}
    <ol class="table">
        {% for conf in object_list %}
        <li class="list-item my-8 rounded-xl border-2 border-separate mx-72 py-10 text-left px-10 pt-5 pb-20 max-w-max">
            <h1 class = "text-3xl max-w-max">{{conf.heading}}</h1>
            <h2 class="mt-3 text-xl text-gray-400 max-w-max">{{conf.text}}</h2>
            
            <a id = "zz" class = "mx-5 text-left text-xl px-5 py-2 text-white bg-red-600 rounded-full" href="{% url 'first_app:deleteView' conf.pk %}">DELETE</a>    
            <style>
                h2{
                    margin-bottom: 30px;
                }
                #zz{
                    margin-left: -2px;
                    
                }
            </style>
            {% if conf.visible == 0 %}
            <a class = "text-left text-xl px-5 py-2 text-white bg-green-500 rounded-full" href="{% url 'first_app:okok' conf.pk %}">ADD</a> 
            {%endif%}
            
        </li>
        
        

        
        {%endfor%}
    </ol>
		{%else%}
    <h1>NO CONFESSIONS</h1>
    {%endif%}
</div>
{%endblock%}

SocialAdda/templates/first_app/confFill.html
<!DOCTYPE html>
{% extends "first_app/start.html" %}
{% block body_block %}


<h1>New Confession:</h1>

<div class = "container">
    <form method = "post">
        {% csrf_token %}
        <div class = "py-5 px-7 mx-5 w-4/5">
            {{form.heading}}
        </div>
        <div class = "px-7 mx-5 ">
            {{form.text}}
        </div>
        <div class="px-2 py-2">
        <button class= "ml-9 mt-3 px-5 py-2 bg-redditNav text-white font-semibold hover:text-redditNav hover:bg-zinc-500 border-zinc-500 hover:border-black border-2 rounded-full">
            Submit
        </button>
        </div>
        
    </form>
</div>
{% endblock %}

SocialAdda/templates/first_app/confList.html
<!DOCTYPE html>
{% extends "first_app/start.html" %}
{% block body_block %}
<h1>Confessions:</h1>
<div class="container text-white px-12 ">
    {% if object_list %}
    <ol class="table text-white ">
        {% for conf in object_list %}
				{% if conf.visible == True %}
        
        <a href="{% url 'first_app:postDetail' conf.pk %}">
          <li class="items-center list-item my-8 rounded-xl border-2 border-separate  text-left px-10 pt-5 pb-20 w-fit max-w-3xl">
          <h1 class = "text-3xl max-w-max">{{conf.heading}}</h1>
						<h2 class="mt-3 text-xl text-gray-400 max-w-max">{{conf.text}}</h2>
        </li></a>
      
				{% endif %}
        {%endfor%}
    </ol>
		{%else%}
    <h1>NO CONFESSIONS</h1>
    {%endif%}
</div>
{%endblock%}

SocialAdda/templates/first_app/postPage.html
<!DOCTYPE html>
{% extends "first_app/start.html" %}
{% block body_block %}

<li class="list-item my-8 rounded-xl border-2 border-separate mx-72 py-10 text-left px-10 pt-5 pb-20">
    <h1 class = "text-white text-3xl max-w-max">{{conf.heading}}</h1>
    <h2 class="mt-3 text-xl text-gray-400 max-w-max">{{conf.text}}</h2>
</li>

<div class="container px-12 ">
    <ol class="table">
        {% for com in all_comments %}
            {% if com.id_conf == conf.pk %}
            <li class="list-item my-8 rounded-md border-2 border-separate mx-72 py-3 text-left px-10 pt-1 pb-12 bg-gray-400">
		<h2 class="mt-4 text-xl text-gray-400 max-w-max">{{com.text}}</h2>
        
        </li>
				{% endif %}
        {%endfor%}
    </ol>
</div>

<div class="">

    <form method = "post">
        {% csrf_token %}
        
        <div class = "relative left-10" style="left: 335px; width: 200px;">
            {{commentForm}}
        </div>
        <div class="">
        <button style="left: 300px;" class= "relative left-10 ml-9 mt-3 px-5 py-2 bg-redditNav text-white font-semibold hover:text-redditNav hover:bg-zinc-500 border-zinc-500 hover:border-black border-2 rounded-full">
            Submit
        </button>
        </div>
        
    </form>

</div>


{%endblock%}

SocialAdda/templates/first_app/start.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% tailwind_css %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <title>start page</title>
</head>

<body class="bg-redditBG">
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'start' %}">SocialAdda</a>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'first_app:adminList' %}">admin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'first_app:confFill' %}">New confession</a>
              </li>
              <li class = "nav-item">
                  <a class = 'nav-link' href="{% url 'first_app:confList' %}">All confessions</a>
              </li>
            </ul>
        </div>
      </nav> -->
      <!-- <nav class="bg-redditNav border-redditBorder border-b-2">
        <div class="px-2 flex justify-between items-center">
            
                <div class=" space-x-4">
                    <div>
                        <a href="#" class="flex items-center py-5 px-10 pt-1">
                            <div class="logo text-red-600 mr-5 mt-5">logo</div>
                            <div class="text-3xl px-2 font-bold font-mono text-white mt-5 pt-0 align-middle mb-0 my-0  invisible sm:visible">SocialAdda</div>
                        </a>
                    </div>
                    
                </div>
                
                <div class="flex search-box py-3">
                <div class="pt-1 relative -mx-48 sm:mx-auto text-gray-500">
                    <input class="border-2 border-zinc-500 hover:border-white bg-searchBar placeholder-gray-300 placeholder-opacity-50 w-72  px-5 pr-16 rounded-md text-sm focus:outline-none sm:w-56 md:w-72 lg:w-72 xl:w-96"
                      type="search" name="search" placeholder="Search">
                    <button type="submit" class="absolute right-2 sm:right-0 -top-1 mt-5 mr-4">
                      <svg class="text-gray-300 text-opacity-50 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
                        viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
                        width="512px" height="512px">
                        <path
                          d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
                      </svg>
                    </button>
                  </div>
                  
                </div>
                <div class=" px-6 flex  items-center space-x-8 pt-1  lg:hidden">
                  <div class="text-right mx-40 
              </div> 
                
                <div class="confess invisible lg:visible">
                    <button class="bg-transparent hover:bg-gray-500 space-x-5 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded-full shadow text-right text-xl text-white confess-button font-bold font-mono drop-shadow-md hover:drop-shadow-xl hover:text-black ">
                    <a href="{% url 'first_app:confFill' %}" class="text-right text-xl text-white confess-button font-bold font-mono drop-shadow-md hover:drop-shadow-xl hover:text-black ">Confess</a>
                    <a href="{% url 'first_app:confList' %}" class="text-right text-xl text-white confess-button font-bold font-mono drop-shadow-md hover:drop-shadow-xl hover:text-black ">Confessions</a>
                    <a href="{% url 'first_app:adminList' %}" class="text-right text-xl text-white confess-button font-bold font-mono drop-shadow-md hover:drop-shadow-xl hover:text-black ">Admin</a>
                  </button>
                </div>
            
         
        </div>
    </nav> -->
    <div class="navbar bg-redditNav border-redditBorder border-b-2 flex justify-between items-center py-1 px-2 ">
      <div class="flex justify-center items-center md:order-2">
        <div class="hamburger inline-block p-4 cursor-pointer md:hidden">
          <div class="line h-0.5 w-6 my-1 bg-white"></div>
          <div class="line h-0.5 w-6 my-1 bg-white"></div>
          <div class="line h-0.5 w-6 my-1 bg-white"></div>
        </div>
        <div class="search text-white md:hidden">
          <svg class="text-white text-opacity-50 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
                        viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
                        width="512px" height="512px">
                        <path
                          d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
                      </svg>
        </div>
        <div class="flex search-box py-3 hidden md:block">
          <div class="pt-1 relative -mx-48 sm:mx-auto text-gray-500">
              <input class="border-2 border-zinc-500 hover:border-white bg-searchBar placeholder-gray-300 placeholder-opacity-50 w-72  px-5 pr-16 rounded-md text-sm focus:outline-none sm:w-56 md:w-72 lg:w-72 xl:w-96"
                type="search" name="search" placeholder="Search">
              <button type="submit" class="absolute right-2 sm:right-0 -top-1 mt-5 mr-4">
                <svg class="text-gray-300 text-opacity-50 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
                  viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
                  width="512px" height="512px">
                  <path
                    d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
                </svg>
              </button>
            </div>
            
          </div>
      </div>
      <div class="logo text-center md:order-1 text-white" ><a href="{% url 'start' %}">SocialAdda</a></div>
      <div class="logo text-center md:hidden text-white">Account</div>
      <div class="confess hidden md:block md:order-3">
        <button class="bg-transparent hover:bg-gray-500 space-x-5 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded-full shadow text-right text-xl text-white confess-button font-bold font-mono drop-shadow-md hover:drop-shadow-xl hover:text-black ">
        <a href="{% url 'first_app:confFill' %}" class="text-right text-xl text-white confess-button font-bold font-mono drop-shadow-md hover:drop-shadow-xl hover:text-black ">Confess</a>
        <a href="{% url 'first_app:confList' %}" class="text-right text-xl text-white confess-button font-bold font-mono drop-shadow-md hover:drop-shadow-xl hover:text-black ">Confessions</a>
        <a href="{% url 'first_app:adminList' %}" class="text-right text-xl text-white confess-button font-bold font-mono drop-shadow-md hover:drop-shadow-xl hover:text-black ">Admin</a>
      </button>
    </div>  
    </div>
    <div class = "container">
        {% block body_block %}
        <!-- only homepage stuff -->
        <h1 class="text-center font-bold text-white text-6xl py-40">homepage</h1>
        {% endblock %}
    </div>
</body>
</html>

SocialAdda/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>